export type HandoverItem = {
    actualFinishDate: string | null;
    actualStartDate: string | null;
    area: string | null;
    commpkgNo: string | null;
    commpkgStatus: string | null;
    createdDate: string | null;
    demolitionActualFinishDate: string | null;
    demolitionActualStartDate: string | null;
    demolitionForecastFinishDate: string | null;
    demolitionForecastStartDate: string | null;
    demolitionPlannedFinishDate: string | null;
    demolitionPlannedStartDate: string | null;
    description: string | null;
    forecastFinishDate: string | null;
    forecastStartDate: string | null;
    forecastTacDate: string | null;
    hasMaintenanceProgram: boolean;
    hasOperationAgreement: boolean;
    hasUnsignedActions: boolean;
    hasYellowLineMarkup: boolean;
    id: string | null;
    isDemolition: boolean;
    isInOperation: boolean;
    isReadyForStartup: boolean;
    isSubsea: boolean;
    mcDisciplineCodes: string[] | null;
    mcDisciplines: string[] | null;
    mcPkgsCount: number;
    mcPkgsRFCCShippedCount: number;
    mcPkgsRFCCSigned: number;
    mcPkgsRFOCShipped: number;
    mcPkgsRFOCSigned: number;
    mcStatus: string | null;
    phase: string | null;
    plannedFinishDate: string | null;
    plannedStartDate: string | null;
    plannedTacDate: string | null;
    priority1: string | null;
    priority2: string | null;
    priority3: string | null;
    progress: string | null;
    projectIdentifier: string | null;
    remark: string | null;
    responsible: string | null;
    rfccIsAccepted: boolean;
    rfccIsRejected: boolean;
    rfccIsShipped: boolean;
    rfocIsAccepted: boolean;
    rfocIsRejected: boolean;
    rfocIsShipped: boolean;
    rowKey: string | null;
    siteCode: string | null;
    subSystem: string | null;
    system: string | null;
    tacIsAccepted: boolean;
    tacIsRejected: boolean;
    tacIsShipped: boolean;
    url: string | null;
    volume: number;
};
