name: PR Build

on:
  pull_request:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: npm install, update version.ts, run tsc, run lint
      run: |
        npm ci
        npm run update-version-definition:no-commit
        npm run tsc
        npm run lint
      env:
        CI: true
